services:
  db:
    image: couchdb:3.5.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=CondimentDouche1!
    ports:
      - 5984:5984
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000